import { Inter } from "next/font/google";
import "./globals.css";
import AppHeader from "@/app/components/AppHeader/AppHeader";
import AppFooter from "@/app/components/AppFooter/AppHeader";
import AppContainer from "@/app/components/AppContainer/AppContainer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AppHeader />

      <AppContainer>
          {children}
      </AppContainer>
      <AppFooter />
      </body>
    </html>
  );
}
