import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import {Suspense} from "react";
import RouteEvent from "@/app/componenets/routeevents";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children,team }) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <div className="sidenav">
            <div >
                <Link href='/'>Home Page</Link>
            </div>
            <div >
                <a href='/products'>Products With A Tag</a>
            </div>
            <div >
                <a href='/categories'>Categories With A Tag</a>
            </div>
            <div >
                <Link href='/products'>Products With Link</Link>
            </div>
            <div >
                <Link href='/categories'>Categories With Link</Link>
            </div>

        </div>

        <div className="main">
            {children}
            <Suspense fallback={null}>
                <RouteEvent />
            </Suspense>
        </div>
        </body>
        </html>
    );
}
